version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root